Repository infi-nl/the-infi-way, pull requests merged in 2023-08, with the labels that each got.

#76 Icons in list
  build/resources/craft.svg
  build/resources/others.svg
  build/resources/principles.svg
  build/resources/process-and-team.svg
  build/resources/source-code.svg
  build/resources/technology.svg
  build/resources/users.svg
  build/style.css
  package-lock.json
  package.json
  template.html
Labels: summer-2023

#79 Updated contributing
  CONTRIBUTING.md
Labels: summer-2023

#78 Improve print styles
  build/style.css
  template.html
Labels: meta, summer-2023

#81 Added: Light mode toggle
  build/bg_icons_lightmode.svg
  build/resources/craft.svg
  build/resources/others.svg
  build/resources/principles.svg
  build/resources/process-and-team.svg
  build/resources/source-code.svg
  build/resources/technology.svg
  build/resources/users.svg
  build/style.css
  content/en.json
  content/nl.json
  template.html
Labels: meta, summer-2023

#83 Fixed: Remove color scheme query from svgs and always use fill: #fff
  build/resources/craft.svg
  build/resources/others.svg
  build/resources/principles.svg
  build/resources/process-and-team.svg
  build/resources/source-code.svg
  build/resources/technology.svg
  build/resources/users.svg
  build/style.css
Labels: bug, summer-2023

#87 Fixed: Replace star unicode character with one that is supported on all OSes
  build/style.css
Labels: bug, summer-2023
